_BASE_: ../Base-bagtricks.yml

MODEL:
  BACKBONE:
    DEPTH: 101x
    WITH_IBN: True

DATASETS:
  NAMES: ("Market1501",)
  TESTS: ("Market1501",)

OUTPUT_DIR: logs/market1501/bagtricks_R101-ibn

MODEL:
  WEIGHTS: checkpoints/fast_-reid/market_bot_R101-ibn.pth